% =========================================================================
% CdS DATA SMOOTHING AND VISUALIZATION
%
% Software and code developed by: MARIO PEZZELLA
%
% This software is associated with the manuscript
%       "Early detection and long-term prediction of pigment degradation in
%        paintings through data-informed mathematical modelling"
%
% Authors:
%       Sara Mattana* and Mario Pezzella*,
%       Francesca Rosi, Marine Cotte, Aldo Romani, Costanza Miliani,
%       Roberto Natalini† and Letizia Monico†
%                         * These authors contributed equally to this work.
%                         † Corresponding authors.
%
% =========================================================================
% This script performs monotonic smoothing of the y-averaged CdS relative
% concentration profiles obtained from the preprocessed synchrotron data.
% The smoothing procedure is based on a functional characterization of the
% space of positive, smooth, and monotonic functions. It exploits a
% regularized combination of Legendre polynomials coupled with a II-order
% ordinary differential equation.
%
% The script first checks whether the preprocessed data are available in
% PreProcessed_Data.mat. If the file is not found, the data processing
% script GH_Data_Processing.m is executed and its generated figures are
% closed immediately.
%
% The smoothed data are saved in Smoothed_Data.mat. If this file already
% exists, the previously computed smoothing results are loaded directly.
%
% The script also generates figures comparing the cropped data with the
% smoothed profiles and figures comparing the smoothing error with the
% standard deviation of the experimental data.
% =========================================================================

%% Data loading
clc; close all
global regolarizer
dataPath = fileparts(mfilename('fullpath'));
dataFile = fullfile(dataPath,'PreProcessed_Data.mat');
smoothedFile = fullfile(dataPath,'Smoothed_Data.mat');

% =========================================================================
% Load preprocessed data
% =========================================================================
if isfile(dataFile)
    fprintf('Loading previously elaborated data.\n');
    load(dataFile);
else
    fprintf('PreProcessed data not found. Running GH_Data_Processing.m.\n');
    run(fullfile(dataPath,'GH_Data_Processing.m'));
    % Close figures generated by the data processing script
    close all
    dataPath = fileparts(mfilename('fullpath'));
    dataFile = fullfile(dataPath,'PreProcessed_Data.mat');
    smoothedFile = fullfile(dataPath,'Smoothed_Data.mat');
end

%% Data normalization
% =========================================================================
% Normalization with respect to the maximum common depth
% =========================================================================
Szs = [size(CdSB1_crop,1) size(CdSD1_crop,1) size(CdSC1_crop,1) ...
       size(CdSC2_crop,1) size(CdSB2_crop,1)];
N_Raw_crop_all = min(Szs);

Adim_C1_mean = CdSC1_crop_mean(1:N_Raw_crop_all);
Adim_D1_mean = CdSD1_crop_mean(1:N_Raw_crop_all);
Adim_B1_mean = CdSB1_crop_mean(1:N_Raw_crop_all);
Adim_B2_mean = CdSB2_crop_mean(1:N_Raw_crop_all);
Adim_C2_mean = CdSC2_crop_mean(1:N_Raw_crop_all);

x_crop_all = dx*(0:1:N_Raw_crop_all-1);
x_crop_adim = x_crop_all/x_crop_all(end);

%% Smoothing procedure
% =========================================================================
% Check whether smoothed data are already available
% =========================================================================
if isfile(smoothedFile)
    fprintf('Loading previously smoothed data.\n');
    load(smoothedFile);
else
    fprintf('Smoothed data not found. Starting smoothing procedure.\n');
    fprintf('\n');

    % =====================================================================
    % Sample t1 (C2) 
    % =====================================================================
    fprintf('Smoothing Sample t1. \n');
    regolarizer = 0.5e-4;
    t_data = x_crop_adim;
    y_data = Adim_C2_mean;
    N_polynomials = 25;
    [W_C2,coeffs_C2] = legendre_fitting(y_data,t_data,N_polynomials);
    fitted_value_C2 = solve_ode(t_data,W_C2(coeffs_C2,t_data),y_data);
    x_dense = linspace(t_data(1),t_data(end),1e4);
    fitted_value_dense_C2 = solve_ode_dense(t_data,x_dense, ...
        W_C2(coeffs_C2,t_data),y_data);
    fitted_value_dense_C2 = min(1,fitted_value_dense_C2);

    % =====================================================================
    % Sample t4 (C1) 
    % =====================================================================
    fprintf('Smoothing Sample t4. \n');
    regolarizer = 0.1e-4;
    t_data = x_crop_adim;
    y_data = Adim_C1_mean;
    N_polynomials = 25;
    [W_C1,coeffs_C1] = legendre_fitting(y_data,t_data,N_polynomials);
    fitted_value_C1 = solve_ode(t_data,W_C1(coeffs_C1,t_data),y_data);
    fitted_value_dense_C1 = solve_ode_dense(t_data,x_dense, ...
        W_C1(coeffs_C1,t_data),y_data);
    fitted_value_dense_C1 = min(1,fitted_value_dense_C1);

    % =====================================================================
    % Sample t7 (D1) 
    % =====================================================================
    fprintf('Smoothing Sample t7. \n');
    regolarizer = 0.1e-4;
    t_data = x_crop_adim;
    y_data = Adim_D1_mean;
    y_data(2) = abs(y_data(5)/y_data(6))*y_data(1);
    N_polynomials = 30;
    [W_D1,coeffs_D1] = legendre_fitting(y_data,t_data,N_polynomials);
    fitted_value_D1 = solve_ode(t_data,W_D1(coeffs_D1,t_data),y_data);
    fitted_value_dense_D1 = solve_ode_dense(t_data,x_dense, ...
        W_D1(coeffs_D1,t_data),y_data);
    fitted_value_dense_D1 = min(1,fitted_value_dense_D1);

    % =====================================================================
    % Sample t9 (B2) 
    % =====================================================================
    fprintf('Smoothing Sample t9. \n');
    regolarizer = 0.05e-4;
    t_data = x_crop_adim;
    y_data = Adim_B2_mean;
    y_data(1) = 0.85;
    y_data(2) = 0.855;
    N_polynomials = 25;
    [W_B2,coeffs_B2] = legendre_fitting(y_data,t_data,N_polynomials);
    fitted_value_B2 = solve_ode(t_data,W_B2(coeffs_B2,t_data),y_data);
    fitted_value_dense_B2 = solve_ode_dense(t_data,x_dense, ...
        W_B2(coeffs_B2,t_data),y_data);
    fitted_value_dense_B2 = min(1,fitted_value_dense_B2);

    % =====================================================================
    % Sample t10 (B1) 
    % =====================================================================
    fprintf('Smoothing Sample t10. \n');
    regolarizer = 3e-4;
    t_data = x_crop_adim;
    y_data = Adim_B1_mean;
    N_polynomials = 25;
    [W_B1,coeffs_B1] = legendre_fitting(y_data,t_data,N_polynomials);
    fitted_value_B1 = solve_ode(t_data,W_B1(coeffs_B1,t_data),y_data);
    fitted_value_dense_B1 = solve_ode_dense(t_data,x_dense, ...
        W_B1(coeffs_B1,t_data),y_data);
    fitted_value_dense_B1 = min(1,fitted_value_dense_B1);

    fprintf('Smoothing procedure completed.\n');
    fprintf('\n');

    % =====================================================================
    % Smoothing errors
    % =====================================================================
    sigma_C1_std_LAST = std(CdSC1_crop(1:N_Raw_crop_all,:),0,2);
    sigma_C2_std_LAST = std(CdSC2_crop(1:N_Raw_crop_all,:),0,2);
    sigma_D1_std_LAST = std(CdSD1_crop(1:N_Raw_crop_all,:),0,2);
    sigma_B1_std_LAST = std(CdSB1_crop(1:N_Raw_crop_all,:),0,2);
    sigma_B2_std_LAST = std(CdSB2_crop(1:N_Raw_crop_all,:),0,2);
    err_C2 = abs(fitted_value_C2-Adim_C2_mean);
    err_C1 = abs(fitted_value_C1-Adim_C1_mean);
    err_D1 = abs(fitted_value_D1-Adim_D1_mean);
    err_B1 = abs(fitted_value_B1-Adim_B1_mean);
    err_B2 = abs(fitted_value_B2-Adim_B2_mean);

    % =====================================================================
    % Save smoothed data
    % =====================================================================
    save(smoothedFile,'-v7.3');
end

%% Plots
% =========================================================================
% Common colour limits and y-axis limits
% =========================================================================
cLim = [min(CdSB1_crop(:)) 1];
miny = 0.98*min([Adim_C2_mean; Adim_C1_mean; Adim_D1_mean; ...
                 Adim_B2_mean; Adim_B1_mean]);
maxy = 1.02*max([Adim_C2_mean; Adim_C1_mean; Adim_D1_mean; ...
                 Adim_B2_mean; Adim_B1_mean]);
x_crop_dense = x_dense*x_crop_all(end);

% =========================================================================
% Cropped data and smoothed profiles
% =========================================================================
figure()
t = tiledlayout(2,5,'TileSpacing','compact','Padding','compact');

% --- First row: cropped data
nexttile
imagesc(y_C2,x_crop_all,CdSC2_crop(1:N_Raw_crop_all,:))
title('C2 - 24 h.')
colormap(jet); ylabel('z (depth) [cm]'); xlabel('y [cm]');
clim(cLim); axis square
nexttile
imagesc(y_C1,x_crop_all,CdSC1_crop(1:N_Raw_crop_all,:))
title('C1 - 80 h.')
colormap(jet); ylabel('z (depth) [cm]'); xlabel('y [cm]');
clim(cLim); axis square
nexttile
imagesc(y_D1,x_crop_all,CdSD1_crop(1:N_Raw_crop_all,:))
title('D1 - 167 h.')
colormap(jet); ylabel('z (depth) [cm]'); xlabel('y [cm]');
clim(cLim); axis square
nexttile
imagesc(y_B2,x_crop_all,CdSB2_crop(1:N_Raw_crop_all,:))
title('B2 - 340 h.')
colormap(jet); ylabel('z (depth) [cm]'); xlabel('y [cm]');
clim(cLim); axis square
nexttile
imagesc(y_B1,x_crop_all,CdSB1_crop(1:N_Raw_crop_all,:))
title('B1 - 680 h.')
colormap(jet); ylabel('z (depth) [cm]'); xlabel('y [cm]');
clim(cLim); axis square

% Colorbar between the two rows
cb = colorbar('southoutside');
cb.Position = [0.062383612662942, 0.553323029366306,...
               0.882681564245810, 0.019134466769706];

% --- Second row: averaged and smoothed data
nexttile
p = fill(x_crop_C2_STD,min(CdSC2_crop_CONF,1),'yellow', ...
    'HandleVisibility','off');
hold on; p.FaceColor = [1 1 0]; p.EdgeColor = 'none'; p.FaceAlpha = 0.2;
semilogy(x_crop_C2,CdSC2_crop_mean,'y','LineWidth',2);
semilogy(x_crop_dense,fitted_value_dense_C2, ...
    'Color',[0.93,0.69,0.13],'LineWidth',2);
title('C2 - 24 h.'); axis square tight; xlim([0 x_crop_dense(end)]);
legend('Avg. Data','Smoothed','Location','southeast')
xlabel('z (depth) [cm]'); ylim([miny maxy]);
nexttile
p = fill(x_crop_C_STD,min(CdSC1_crop_CONF,1),'green', ...
    'HandleVisibility','off');
hold on; p.FaceColor = [0.43,0.79,0.43]; 
p.EdgeColor = 'none'; p.FaceAlpha = 0.2;
semilogy(x_crop_C,CdSC1_crop_mean,'g','LineWidth',2);
semilogy(x_crop_dense,fitted_value_dense_C1, ...
    'Color',[0,0.35,0],'LineWidth',2);
title('C1 - 80 h.'); axis square tight; xlim([0 x_crop_dense(end)]);
legend('Avg. Data','Smoothed','Location','southeast')
xlabel('z (depth) [cm]'); ylim([miny maxy]);
nexttile
p = fill(x_crop_D_STD,min(CdSD1_crop_CONF,1),'red', ...
    'HandleVisibility','off');
hold on; p.FaceColor = [0.99,0.62,0.60]; 
p.EdgeColor = 'none'; p.FaceAlpha = 0.2;
semilogy(x_crop_D,CdSD1_crop_mean,'r','LineWidth',2);
semilogy(x_crop_dense,fitted_value_dense_D1, ...
    'Color',[0.35,0,0],'LineWidth',2);
title('D1 - 167 h.'); axis square tight; xlim([0 x_crop_dense(end)]);
legend('Avg. Data','Smoothed','Location','southeast')
xlabel('z (depth) [cm]'); ylim([miny maxy]);
nexttile
p = fill(x_crop_B2_STD,min(CdSB2_crop_CONF,1),'red', ...
    'HandleVisibility','off');
hold on; p.FaceColor = [0.72,0.27,1.00]; 
p.EdgeColor = 'none'; p.FaceAlpha = 0.2;
semilogy(x_crop_B2,CdSB2_crop_mean,'m','LineWidth',2);
semilogy(x_crop_dense,fitted_value_dense_B2, ...
    'Color',[0.49,0.18,0.56],'LineWidth',2);
title('B2 - 340 h.'); axis square tight; xlim([0 x_crop_dense(end)]);
legend('Avg. Data','Smoothed','Location','southeast')
xlabel('z (depth) [cm]'); ylim([miny maxy]);
nexttile
p = fill(x_crop_B_STD,min(CdSB1_crop_CONF,1),'red', ...
    'HandleVisibility','off');
hold on; p.FaceColor = [0.06,1.00,1.00]; 
p.EdgeColor = 'none'; p.FaceAlpha = 0.2;
semilogy(x_crop_B,CdSB1_crop_mean,'b','LineWidth',2);
semilogy(x_crop_dense,fitted_value_dense_B1, ...
    'Color',[0,0,0.35],'LineWidth',2);
title('B1 - 680 h.'); axis square tight; xlim([0 x_crop_dense(end)]);
legend('Avg. Data','Smoothed','Location','southeast')
xlabel('z (depth) [cm]'); ylim([miny maxy]);

% Global titles
annotation('textbox',[0 0.93 1 0.05], ...
    'String','Relative CdS Concentrations - Cropped Shifted Data ', ...
    'EdgeColor','none','HorizontalAlignment','center', ...
    'FontWeight','bold','FontSize',12);
annotation('textbox',[0, 0.4329057187017, 1, 0.05], ...
    'String','Relative CdS Concentrations - Averaged and Smoothed Data', ...
    'EdgeColor','none','HorizontalAlignment','center', ...
    'FontWeight','bold','FontSize',12);

% =========================================================================
% Smoothing errors compared to data standard deviation
% =========================================================================
figure()

% Positions [left bottom width height] in normalized units [0,1]
pos_top = [0.05 0.55 0.27 0.35;
           0.37 0.55 0.27 0.35;
           0.69 0.55 0.27 0.35];
pos_bottom = [0.21 0.1 0.27 0.35;
              0.53 0.1 0.27 0.35];

% --- First row
axes('Position',pos_top(1,:));
semilogy(x_crop_all,err_C2,'*y','LineWidth',1.5, ...
    'Color',[0.93,0.69,0.13]); hold on
semilogy(x_crop_all,sigma_C2_std_LAST,'sy','LineWidth',1.5);
legend('Smoothing Err.','Data Std. Dev.','Location','southeast')
axis square tight
title('C2 - 24 h.'); xlabel('z (depth) [cm]');
axes('Position',pos_top(2,:));
semilogy(x_crop_all,err_C1,'*','LineWidth',1.5, ...
    'Color',[0.00,0.35,0.00]); hold on
semilogy(x_crop_all,sigma_C1_std_LAST,'sg','LineWidth',1.5);
legend('Smoothing Err.','Data Std. Dev.','Location','southeast')
axis square tight
title('C1 - 80 h.'); xlabel('z (depth) [cm]');
axes('Position',pos_top(3,:));
semilogy(x_crop_all,err_D1,'*','LineWidth',1.5, ...
    'Color',[0.35,0,0]); hold on
semilogy(x_crop_all,sigma_D1_std_LAST,'sr','LineWidth',1.5);
legend('Smoothing Err.','Data Std. Dev.','Location','southeast')
axis square tight
title('D1 - 167 h.'); xlabel('z (depth) [cm]');

% --- Second row
axes('Position',pos_bottom(1,:));
semilogy(x_crop_all,err_B2,'*','Color',[0.49,0.18,0.56], ...
    'LineWidth',1.5); hold on
semilogy(x_crop_all,sigma_B2_std_LAST,'s', ...
    'LineWidth',1.5,'Color',[1.00,0.00,1.00]);
legend('Smoothing Err.','Data Std. Dev.','Location','southeast')
axis square tight
title('B2 - 340 h.'); xlabel('z (depth) [cm]');
axes('Position',pos_bottom(2,:));
semilogy(x_crop_all,err_B1,'*','LineWidth',1.5, ...
    'Color',[0.00,0.00,0.35]); hold on
semilogy(x_crop_all,sigma_B1_std_LAST,'s', ...
    'LineWidth',1.5,'Color',[0.00,0.00,1.00]);
legend('Smoothing Err.','Data Std. Dev.','Location','southeast')
axis square tight
title('B1 - 680 h.'); xlabel('z (depth) [cm]');
% Global title
annotation('textbox',[0 0.93 1 0.05], ...
    'String','Smoothing Errors compared to Data Standard Deviation ', ...
    'EdgeColor','none','HorizontalAlignment','center', ...
    'FontWeight','bold','FontSize',12);

% =========================================================================
% Local functions
% =========================================================================
function [W,coeffs] = legendre_fitting(y_data,t_data,N)
    global regolarizer
    n = length(t_data);
    a = t_data(1);
    b = t_data(end);
    t_shift = 2*(t_data-a)/(b-a)-1;
    P = zeros(n,N);
    for k = 1:N
        P(:,k) = legendreP(k-1,t_shift);
    end
    W = @(c,t) P*c;
    regolar = (b-a)./(1+2*(0:1:N-1));
    errorFunc = @(c) norm(y_data-solve_ode(t_data,W(c,t_data),y_data),2)^2 ...
                     + regolarizer.*(regolar*c.^2);
    initial_guess = zeros(N,1);
    options = optimoptions('fmincon','Algorithm','interior-point', ...
        'Display','off','MaxFunctionEvaluations',9e3, ...
        'OptimalityTolerance',1e-14,'StepTolerance',1e-14, ...
        'UseParallel',true);
    coeffs = fmincon(errorFunc,initial_guess,[],[],[],[],[],[],[],options);
end

function f_vals = solve_ode(t_data,w_values,y_data)
    % The II order ODE f''(t) = w(t) f'(t) is numerically solved with ode45
    f0 = min(y_data);
    f0_prime = abs((y_data(1)-y_data(2))/(t_data(1)-t_data(2)));
    w_interp = @(t) interp1(t_data,w_values,t,'spline','extrap');
    odeFunc = @(t,f) [f(2); w_interp(t)*f(2)];
    [~,f_sol] = ode45(odeFunc,t_data,[f0; f0_prime]);
    f_vals = f_sol(:,1);
end

function f_vals = solve_ode_dense(t_data,x_dense,w_values,y_data)
    f0 = min(y_data);
    f0_prime = abs((y_data(1)-y_data(2))/(t_data(1)-t_data(2)));
    w_interp = @(t) interp1(t_data,w_values,t,'spline','extrap');
    odeFunc = @(t,f) [f(2); w_interp(t)*f(2)];
    [~,f_sol] = ode45(odeFunc,x_dense,[f0; f0_prime]);
    f_vals = f_sol(:,1);
end